# baseURL = "http://0.0.0.0"
languageCode = "en-us"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
theme = ["MoonLake"]
title = "凉风有信 秋月无边"
hasCJKLanguage = true

[frontmatter]
  lastmod = [":git", ":fileModTime", "lastmod"]

[Menus]
  main = [
	{Name = "文章", URL = "/posts/", weight = "1"},
	{Name = "分类", URL = "/categories", weight = "2"},
	{Name = "关于", URL = "/about/", weight = "9"},
  ]


[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "doom-one"

[params]
author = "大悦帮帮忙"
info = "月落乌啼霜满天 江枫渔火对愁眠"
description = "by Jack Hu"
pagetitle = "凉风有信"
avatarurl = "avatar.jpg"
hideColorSchemeToggle=true
copyright = "大悦帮帮忙"
since = 2022
paginate = 20

# favicon_16 = "static/favicon.ico"

dateformShort   = "1月2日"
dateFormat = "2006-01-02 15:04"
dateNum = "2006-01-02"

# customCSS = ["css/extra.css"]
# customJS = ["js/lazysizes.min.js"]

[[params.social]]
name = "WeChat"
icon = "fa fa-wechat fa-2x"
weight = 1
url = "#"

[[params.social]]
name = "GitHub"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://www.github.com/"

[[params.social]]
name = "Email"
icon = "fa fa-envelope fa-2x"
weight = 3
url = "mailto:530048576@qq.com"
